"""Curated skill/title/location/industry taxonomy — the normalization backbone.

Single source of truth for:
- skill canonicalization (aliases → canonical name, categories, related edges),
- title normalization (seniority + role family extraction),
- location parsing (city aliases → city/country),
- industry/domain keyword sets.

Used by the seed generator, resume/JD ingestion, the demo embedder (query
expansion) and the rule-based NL query parser. Deliberately curated and small
enough to read in one sitting — RecruitAgent-style "auditable by design".
"""

from __future__ import annotations

SENIORITY_ORDER = ["intern", "junior", "mid", "senior", "lead", "principal", "staff", "head"]

SENIORITY_WORDS: dict[str, list[str]] = {
    "intern": ["intern", "internship", "trainee"],
    "junior": ["junior", "jr", "entry level", "entry-level", "graduate"],
    "mid": ["mid level", "mid-level", "intermediate", " ii", " iii"],
    "senior": ["senior", "sr"],
    "lead": ["lead", "team lead", "tech lead", "engineering lead"],
    "staff": ["staff"],
    "principal": ["principal"],
    "head": ["head of", "director", "vp of", "vice president", "chief", "manager of engineering"],
}

# Role families: keywords (in priority order per family) used to classify a title.
TITLE_FAMILIES: dict[str, list[str]] = {
    "mobile engineer": [
        "ios engineer",
        "android engineer",
        "mobile engineer",
        "mobile developer",
        "ios developer",
        "android developer",
    ],
    "data engineer": ["data engineer", "analytics engineer", "etl developer", "data platform"],
    "ml engineer": [
        "machine learning engineer",
        "ml engineer",
        "ai engineer",
        "mlops",
        "deep learning engineer",
        "nlp engineer",
    ],
    "data scientist": ["data scientist", "research scientist", "applied scientist"],
    "data analyst": ["data analyst", "business analyst", "bi analyst", "analytics analyst"],
    "devops engineer": [
        "devops",
        "sre",
        "site reliability",
        "platform engineer",
        "cloud engineer",
        "infrastructure engineer",
    ],
    "security engineer": [
        "security engineer",
        "appsec",
        "security analyst",
        "soc analyst",
        "penetration tester",
    ],
    "qa engineer": ["qa engineer", "qa analyst", "test engineer", "sdet", "quality assurance"],
    "frontend engineer": ["frontend", "front-end", "front end", "ui engineer", "react developer"],
    "backend engineer": [
        "backend",
        "back-end",
        "back end",
        "api engineer",
        "server engineer",
        "software engineer, backend",
    ],
    "fullstack engineer": ["fullstack", "full-stack", "full stack"],
    "software engineer": ["software engineer", "software developer", "programmer", "developer"],
    "engineering manager": ["engineering manager", "em ", "director of engineering"],
    "product manager": ["product manager", "product owner", "pm,", "group product"],
    "product designer": [
        "product designer",
        "ux designer",
        "ui designer",
        "ux/ui",
        "interaction designer",
    ],
    "recruiter": ["recruiter", "sourcer", "talent acquisition", "talent partner", "recruiting"],
    "sales": [
        "account executive",
        "sales representative",
        "business development",
        "account manager",
        "sales manager",
        "sales development",
    ],
    "marketing": [
        "marketing manager",
        "growth manager",
        "seo specialist",
        "content marketer",
        "demand generation",
        "brand manager",
    ],
    "customer success": [
        "customer success",
        "customer support",
        "support engineer",
        "customer experience",
    ],
    "finance": [
        "financial analyst",
        "accountant",
        "finance manager",
        "controller",
        "fp&a",
        "treasury",
    ],
    "operations": [
        "operations manager",
        "ops manager",
        "supply chain",
        "logistics manager",
        "procurement",
        "warehouse manager",
    ],
    "hr": ["hr manager", "people partner", "people ops", "human resources"],
}

# Canonical skills: canonical → {category, aliases, related}
SKILLS: dict[str, dict] = {
    # ── languages ─────────────────────────────────────────────────────────
    "python": {
        "category": "language",
        "aliases": ["python3", "py"],
        "related": ["django", "flask", "fastapi", "pandas"],
    },
    "javascript": {
        "category": "language",
        "aliases": ["js", "es6", "ecmascript"],
        "related": ["typescript", "nodejs", "react"],
    },
    "typescript": {
        "category": "language",
        "aliases": ["ts"],
        "related": ["javascript", "react", "nextjs"],
    },
    "java": {
        "category": "language",
        "aliases": ["java 8", "java 11", "java 17"],
        "related": ["spring", "kotlin"],
    },
    "go": {"category": "language", "aliases": ["golang"], "related": ["kubernetes", "grpc"]},
    "rust": {"category": "language", "aliases": [], "related": ["cpp"]},
    "ruby": {"category": "language", "aliases": [], "related": ["rails"]},
    "php": {"category": "language", "aliases": [], "related": ["laravel"]},
    "csharp": {"category": "language", "aliases": ["c#", "c sharp"], "related": ["dotnet"]},
    "dotnet": {
        "category": "framework",
        "aliases": [".net", "asp.net", "net core"],
        "related": ["csharp"],
    },
    "cpp": {"category": "language", "aliases": ["c++"], "related": ["rust"]},
    "kotlin": {"category": "language", "aliases": [], "related": ["android", "java"]},
    "swift": {"category": "language", "aliases": ["swiftui"], "related": ["ios"]},
    "scala": {"category": "language", "aliases": [], "related": ["spark", "java"]},
    "sql": {"category": "language", "aliases": [], "related": ["postgresql", "mysql"]},
    "r": {"category": "language", "aliases": ["r language"], "related": ["statistics"]},
    # ── frontend ──────────────────────────────────────────────────────────
    "react": {
        "category": "framework",
        "aliases": ["react.js", "reactjs"],
        "related": ["javascript", "nextjs", "vue"],
    },
    "vue": {
        "category": "framework",
        "aliases": ["vue.js", "vuejs"],
        "related": ["javascript", "react"],
    },
    "angular": {
        "category": "framework",
        "aliases": ["angularjs"],
        "related": ["typescript", "react"],
    },
    "svelte": {"category": "framework", "aliases": ["sveltekit"], "related": ["javascript"]},
    "nextjs": {
        "category": "framework",
        "aliases": ["next.js", "next js"],
        "related": ["react", "typescript"],
    },
    "tailwind": {"category": "framework", "aliases": ["tailwindcss"], "related": ["css"]},
    "css": {
        "category": "framework",
        "aliases": ["css3", "scss", "sass"],
        "related": ["html", "tailwind"],
    },
    "html": {"category": "framework", "aliases": ["html5"], "related": ["css"]},
    "redux": {"category": "framework", "aliases": ["redux toolkit"], "related": ["react"]},
    "accessibility": {
        "category": "practices",
        "aliases": ["a11y", "wcag"],
        "related": ["frontend"],
    },
    # ── backend / APIs ────────────────────────────────────────────────────
    "django": {"category": "framework", "aliases": ["django rest"], "related": ["python"]},
    "flask": {"category": "framework", "aliases": [], "related": ["python"]},
    "fastapi": {"category": "framework", "aliases": [], "related": ["python", "rest"]},
    "nodejs": {
        "category": "framework",
        "aliases": ["node", "node.js"],
        "related": ["javascript", "express"],
    },
    "express": {"category": "framework", "aliases": ["express.js"], "related": ["nodejs"]},
    "spring": {"category": "framework", "aliases": ["spring boot"], "related": ["java"]},
    "rails": {"category": "framework", "aliases": ["ruby on rails"], "related": ["ruby"]},
    "laravel": {"category": "framework", "aliases": [], "related": ["php"]},
    "graphql": {"category": "framework", "aliases": [], "related": ["rest"]},
    "rest": {
        "category": "practices",
        "aliases": ["rest apis", "restful", "rest api"],
        "related": ["graphql", "api design"],
    },
    "grpc": {
        "category": "framework",
        "aliases": ["protobuf", "protocol buffers"],
        "related": ["microservices"],
    },
    "microservices": {
        "category": "practices",
        "aliases": ["micro-services"],
        "related": ["docker", "kubernetes"],
    },
    "api design": {
        "category": "practices",
        "aliases": ["api development", "api integrations"],
        "related": ["rest"],
    },
    # ── mobile ────────────────────────────────────────────────────────────
    "react-native": {
        "category": "framework",
        "aliases": ["react native"],
        "related": ["react", "mobile"],
    },
    "flutter": {"category": "framework", "aliases": ["dart"], "related": ["mobile"]},
    "ios": {"category": "platform", "aliases": ["ios development"], "related": ["swift", "mobile"]},
    "android": {
        "category": "platform",
        "aliases": ["android development"],
        "related": ["kotlin", "mobile"],
    },
    "mobile": {
        "category": "domain",
        "aliases": ["mobile development", "mobile apps"],
        "related": ["ios", "android", "react-native"],
    },
    # ── databases / data stores ───────────────────────────────────────────
    "postgresql": {
        "category": "database",
        "aliases": ["postgres", "psql"],
        "related": ["sql", "mysql"],
    },
    "mysql": {"category": "database", "aliases": ["mariadb"], "related": ["sql", "postgresql"]},
    "mongodb": {"category": "database", "aliases": ["mongo"], "related": ["nosql"]},
    "nosql": {"category": "database", "aliases": ["no-sql"], "related": ["mongodb", "redis"]},
    "redis": {"category": "database", "aliases": ["redis cache"], "related": ["caching"]},
    "elasticsearch": {
        "category": "database",
        "aliases": ["elastic search", "opensearch"],
        "related": ["search"],
    },
    "sqlite": {"category": "database", "aliases": [], "related": ["sql"]},
    "oracle": {"category": "database", "aliases": ["oracle db"], "related": ["sql"]},
    "snowflake": {"category": "database", "aliases": [], "related": ["data warehouse", "bigquery"]},
    "bigquery": {"category": "database", "aliases": ["big query"], "related": ["gcp", "snowflake"]},
    "dynamodb": {"category": "database", "aliases": ["dynamo db"], "related": ["aws", "nosql"]},
    "data warehouse": {
        "category": "database",
        "aliases": ["data warehousing", "warehouse"],
        "related": ["snowflake", "dbt"],
    },
    "vector database": {
        "category": "database",
        "aliases": ["vectordb", "pgvector", "vector store"],
        "related": ["embeddings", "search"],
    },
    # ── cloud / devops ────────────────────────────────────────────────────
    "aws": {
        "category": "cloud",
        "aliases": ["amazon web services", "ec2", "s3"],
        "related": ["cloud", "terraform"],
    },
    "gcp": {
        "category": "cloud",
        "aliases": ["google cloud", "google cloud platform"],
        "related": ["cloud", "bigquery"],
    },
    "azure": {"category": "cloud", "aliases": ["microsoft azure"], "related": ["cloud", "dotnet"]},
    "cloud": {
        "category": "cloud",
        "aliases": ["cloud computing", "cloud infrastructure"],
        "related": ["aws", "gcp", "azure"],
    },
    "docker": {
        "category": "devops",
        "aliases": ["containerization", "containers", "dockerfiles"],
        "related": ["kubernetes", "ci-cd"],
    },
    "kubernetes": {
        "category": "devops",
        "aliases": ["k8s", "eks", "gke"],
        "related": ["docker", "helm"],
    },
    "terraform": {
        "category": "devops",
        "aliases": ["iac", "infrastructure as code"],
        "related": ["aws", "ansible"],
    },
    "ansible": {"category": "devops", "aliases": [], "related": ["terraform", "linux"]},
    "jenkins": {"category": "devops", "aliases": [], "related": ["ci-cd"]},
    "github-actions": {"category": "devops", "aliases": ["github actions"], "related": ["ci-cd"]},
    "gitlab-ci": {"category": "devops", "aliases": ["gitlab ci"], "related": ["ci-cd"]},
    "ci-cd": {
        "category": "devops",
        "aliases": ["ci/cd", "continuous integration", "continuous delivery", "pipelines"],
        "related": ["jenkins", "github-actions", "docker"],
    },
    "linux": {
        "category": "devops",
        "aliases": ["unix", "bash", "shell scripting"],
        "related": ["nginx"],
    },
    "nginx": {"category": "devops", "aliases": [], "related": ["linux"]},
    "monitoring": {
        "category": "devops",
        "aliases": ["observability", "grafana", "prometheus", "datadog"],
        "related": ["devops engineer"],
    },
    "git": {
        "category": "devops",
        "aliases": ["github", "gitlab", "version control"],
        "related": ["ci-cd"],
    },
    "helm": {"category": "devops", "aliases": [], "related": ["kubernetes"]},
    # ── data / ml ─────────────────────────────────────────────────────────
    "pandas": {"category": "data", "aliases": ["numpy"], "related": ["python", "data-analysis"]},
    "spark": {
        "category": "data",
        "aliases": ["pyspark", "apache spark"],
        "related": ["scala", "big data"],
    },
    "airflow": {
        "category": "data",
        "aliases": ["apache airflow"],
        "related": ["etl", "orchestration"],
    },
    "kafka": {
        "category": "data",
        "aliases": ["apache kafka", "event streaming", "kinesis"],
        "related": ["streaming", "spark"],
    },
    "dbt": {"category": "data", "aliases": [], "related": ["sql", "data warehouse"]},
    "etl": {
        "category": "data",
        "aliases": ["elt", "data pipelines", "data pipeline"],
        "related": ["airflow", "dbt"],
    },
    "orchestration": {
        "category": "data",
        "aliases": ["workflow orchestration"],
        "related": ["airflow"],
    },
    "big data": {"category": "data", "aliases": ["hadoop"], "related": ["spark", "kafka"]},
    "streaming": {
        "category": "data",
        "aliases": ["real-time", "real time data"],
        "related": ["kafka"],
    },
    "machine-learning": {
        "category": "ml",
        "aliases": ["machine learning", "ml"],
        "related": ["pytorch", "tensorflow", "deep-learning"],
    },
    "deep-learning": {
        "category": "ml",
        "aliases": ["deep learning", "neural networks"],
        "related": ["pytorch", "tensorflow"],
    },
    "pytorch": {"category": "ml", "aliases": ["torch"], "related": ["python", "deep-learning"]},
    "tensorflow": {"category": "ml", "aliases": ["keras"], "related": ["deep-learning"]},
    "scikit-learn": {
        "category": "ml",
        "aliases": ["scikit learn", "sklearn"],
        "related": ["python", "machine-learning"],
    },
    "nlp": {
        "category": "ml",
        "aliases": ["natural language processing", "text mining"],
        "related": ["llm", "transformers"],
    },
    "llm": {
        "category": "ml",
        "aliases": ["large language models", "gpt", "language models"],
        "related": ["nlp", "rag", "prompt-engineering"],
    },
    "rag": {
        "category": "ml",
        "aliases": ["retrieval augmented generation", "retrieval-augmented"],
        "related": ["llm", "embeddings", "vector database"],
    },
    "embeddings": {
        "category": "ml",
        "aliases": ["embedding models", "sentence embeddings", "vector embeddings"],
        "related": ["vector database", "semantic search"],
    },
    "semantic search": {
        "category": "ml",
        "aliases": ["semantic retrieval", "neural search"],
        "related": ["embeddings", "search"],
    },
    "search": {
        "category": "domain",
        "aliases": ["search systems", "information retrieval", "ir"],
        "related": ["elasticsearch", "semantic search"],
    },
    "recommender-systems": {
        "category": "ml",
        "aliases": ["recommendation systems", "recommenders"],
        "related": ["machine-learning"],
    },
    "computer-vision": {
        "category": "ml",
        "aliases": ["computer vision", "opencv", "image recognition"],
        "related": ["deep-learning"],
    },
    "prompt-engineering": {"category": "ml", "aliases": ["prompt design"], "related": ["llm"]},
    "transformers": {
        "category": "ml",
        "aliases": ["hugging face", "huggingface"],
        "related": ["nlp", "pytorch"],
    },
    "statistics": {
        "category": "data",
        "aliases": ["statistical analysis", "statistical modeling"],
        "related": ["r", "a-b-testing"],
    },
    "a-b-testing": {
        "category": "data",
        "aliases": ["ab testing", "a/b testing", "experimentation"],
        "related": ["statistics"],
    },
    "data-analysis": {
        "category": "data",
        "aliases": ["data analysis", "data analytics"],
        "related": ["sql", "pandas"],
    },
    "data-viz": {
        "category": "data",
        "aliases": ["data visualization", "tableau", "power bi", "looker"],
        "related": ["data-analysis"],
    },
    "excel": {
        "category": "data",
        "aliases": ["spreadsheets", "google sheets"],
        "related": ["financial-modeling"],
    },
    # ── product / design ──────────────────────────────────────────────────
    "product-management": {
        "category": "product",
        "aliases": ["product management", "product strategy"],
        "related": ["roadmapping", "user-research"],
    },
    "roadmapping": {
        "category": "product",
        "aliases": ["roadmap", "backlog grooming", "prioritization"],
        "related": ["product-management", "agile"],
    },
    "user-research": {
        "category": "product",
        "aliases": ["user interviews", "usability testing"],
        "related": ["ux design"],
    },
    "figma": {"category": "design", "aliases": [], "related": ["ux design", "prototyping"]},
    "ux design": {
        "category": "design",
        "aliases": ["ux", "ui/ux", "user experience"],
        "related": ["figma", "design systems"],
    },
    "ui design": {
        "category": "design",
        "aliases": ["ui", "visual design"],
        "related": ["figma", "design systems"],
    },
    "design systems": {
        "category": "design",
        "aliases": ["design system", "component library"],
        "related": ["ui design", "frontend engineer"],
    },
    "prototyping": {
        "category": "design",
        "aliases": ["wireframing", "mockups"],
        "related": ["figma", "ux design"],
    },
    "agile": {
        "category": "practices",
        "aliases": ["scrum", "kanban", "sprint planning"],
        "related": ["jira", "roadmapping"],
    },
    "jira": {"category": "practices", "aliases": ["confluence", "atlassian"], "related": ["agile"]},
    "project-management": {
        "category": "practices",
        "aliases": ["project delivery", "program management"],
        "related": ["agile", "stakeholder management"],
    },
    # ── marketing / sales / support ───────────────────────────────────────
    "seo": {
        "category": "marketing",
        "aliases": ["search engine optimization"],
        "related": ["content marketing"],
    },
    "content marketing": {
        "category": "marketing",
        "aliases": ["content strategy", "copywriting"],
        "related": ["seo", "brand"],
    },
    "paid-ads": {
        "category": "marketing",
        "aliases": ["ppc", "google ads", "paid social"],
        "related": ["marketing"],
    },
    "marketing": {
        "category": "marketing",
        "aliases": ["demand generation", "growth marketing", "brand"],
        "related": ["seo", "paid-ads"],
    },
    "crm": {
        "category": "sales",
        "aliases": ["salesforce", "hubspot"],
        "related": ["b2b sales", "account management"],
    },
    "b2b sales": {
        "category": "sales",
        "aliases": ["b2b sales", "enterprise sales", "saas sales", "outbound"],
        "related": ["crm", "lead generation"],
    },
    "lead generation": {
        "category": "sales",
        "aliases": ["lead gen", "prospecting", "cold outreach"],
        "related": ["crm"],
    },
    "account management": {
        "category": "sales",
        "aliases": ["account management", "client relations", "relationship management"],
        "related": ["customer success", "b2b sales"],
    },
    "customer success": {
        "category": "support",
        "aliases": ["customer success", "customer onboarding", "account success"],
        "related": ["account management", "support"],
    },
    "support": {
        "category": "support",
        "aliases": ["customer support", "helpdesk", "technical support", "zendesk", "freshdesk"],
        "related": ["customer success"],
    },
    # ── finance / ops / hr ────────────────────────────────────────────────
    "accounting": {
        "category": "finance",
        "aliases": ["bookkeeping", "accounts payable", "accounts receivable", "ifrs"],
        "related": ["financial-modeling", "excel"],
    },
    "financial-modeling": {
        "category": "finance",
        "aliases": ["financial analysis", "fp&a", "budgeting", "forecasting"],
        "related": ["excel", "accounting"],
    },
    "audit": {
        "category": "finance",
        "aliases": ["internal audit", "external audit", "compliance"],
        "related": ["accounting", "risk"],
    },
    "risk": {
        "category": "finance",
        "aliases": ["risk management", "credit risk"],
        "related": ["audit", "compliance"],
    },
    "compliance": {
        "category": "finance",
        "aliases": ["regulatory", "kyc", "aml"],
        "related": ["audit", "risk"],
    },
    "supply-chain": {
        "category": "ops",
        "aliases": ["supply chain", "logistics", "warehouse", "inventory management", "freight"],
        "related": ["operations", "procurement"],
    },
    "procurement": {
        "category": "ops",
        "aliases": ["purchasing", "vendor management", "sourcing"],
        "related": ["supply-chain"],
    },
    "operations": {
        "category": "ops",
        "aliases": ["business operations", "operations management", "process improvement"],
        "related": ["supply-chain", "project-management"],
    },
    "recruiting": {
        "category": "hr",
        "aliases": ["talent acquisition", "sourcing", "technical recruiting", "hiring"],
        "related": ["ats", "screening"],
    },
    "ats": {
        "category": "hr",
        "aliases": ["applicant tracking", "greenhouse", "lever", "workable"],
        "related": ["recruiting"],
    },
    "screening": {
        "category": "hr",
        "aliases": ["candidate screening", "interviewing"],
        "related": ["recruiting"],
    },
    "hr": {
        "category": "hr",
        "aliases": ["human resources", "people ops", "people operations", "payroll"],
        "related": ["recruiting", "onboarding"],
    },
    "onboarding": {"category": "hr", "aliases": ["employee onboarding"], "related": ["hr"]},
    # ── cross-cutting ─────────────────────────────────────────────────────
    "communication": {
        "category": "soft",
        "aliases": ["stakeholder communication", "presentation skills"],
        "related": ["stakeholder management"],
    },
    "leadership": {
        "category": "soft",
        "aliases": ["team leadership", "people management", "mentoring", "coaching"],
        "related": ["communication"],
    },
    "stakeholder management": {
        "category": "soft",
        "aliases": ["stakeholder management", "cross-functional collaboration"],
        "related": ["communication"],
    },
    "technical-writing": {
        "category": "soft",
        "aliases": ["documentation", "knowledge base"],
        "related": ["communication"],
    },
    "mentorship": {
        "category": "soft",
        "aliases": ["mentoring", "coaching", "code reviews"],
        "related": ["leadership"],
    },
}

# Location aliases → (city, country, region). Country-only aliases resolve to the
# country's primary city for this demo dataset.
LOCATIONS: dict[str, tuple[str, str, str]] = {
    # GCC (this portfolio's home region)
    "dubai": ("Dubai", "United Arab Emirates", "MENA"),
    "abu dhabi": ("Abu Dhabi", "United Arab Emirates", "MENA"),
    "sharjah": ("Sharjah", "United Arab Emirates", "MENA"),
    "riyadh": ("Riyadh", "Saudi Arabia", "MENA"),
    "jeddah": ("Jeddah", "Saudi Arabia", "MENA"),
    "doha": ("Doha", "Qatar", "MENA"),
    "kuwait city": ("Kuwait City", "Kuwait", "MENA"),
    "manama": ("Manama", "Bahrain", "MENA"),
    "muscat": ("Muscat", "Oman", "MENA"),
    "cairo": ("Cairo", "Egypt", "MENA"),
    "amman": ("Amman", "Jordan", "MENA"),
    "beirut": ("Beirut", "Lebanon", "MENA"),
    # Europe
    "berlin": ("Berlin", "Germany", "Europe"),
    "munich": ("Munich", "Germany", "Europe"),
    "frankfurt": ("Frankfurt", "Germany", "Europe"),
    "london": ("London", "United Kingdom", "Europe"),
    "manchester": ("Manchester", "United Kingdom", "Europe"),
    "dublin": ("Dublin", "Ireland", "Europe"),
    "amsterdam": ("Amsterdam", "Netherlands", "Europe"),
    "paris": ("Paris", "France", "Europe"),
    "madrid": ("Madrid", "Spain", "Europe"),
    "barcelona": ("Barcelona", "Spain", "Europe"),
    "lisbon": ("Lisbon", "Portugal", "Europe"),
    "warsaw": ("Warsaw", "Poland", "Europe"),
    "prague": ("Prague", "Czechia", "Europe"),
    "vienna": ("Vienna", "Austria", "Europe"),
    "zurich": ("Zurich", "Switzerland", "Europe"),
    "stockholm": ("Stockholm", "Sweden", "Europe"),
    "copenhagen": ("Copenhagen", "Denmark", "Europe"),
    "helsinki": ("Helsinki", "Finland", "Europe"),
    "tallinn": ("Tallinn", "Estonia", "Europe"),
    "istanbul": ("Istanbul", "Türkiye", "Europe"),
    # Americas / APAC / Africa
    "toronto": ("Toronto", "Canada", "Americas"),
    "vancouver": ("Vancouver", "Canada", "Americas"),
    "new york": ("New York", "United States", "Americas"),
    "san francisco": ("San Francisco", "United States", "Americas"),
    "austin": ("Austin", "United States", "Americas"),
    "seattle": ("Seattle", "United States", "Americas"),
    "boston": ("Boston", "United States", "Americas"),
    "chicago": ("Chicago", "United States", "Americas"),
    "singapore": ("Singapore", "Singapore", "APAC"),
    "kuala lumpur": ("Kuala Lumpur", "Malaysia", "APAC"),
    "bengaluru": ("Bengaluru", "India", "APAC"),
    "bangalore": ("Bengaluru", "India", "APAC"),
    "mumbai": ("Mumbai", "India", "APAC"),
    "delhi": ("Delhi", "India", "APAC"),
    "hyderabad": ("Hyderabad", "India", "APAC"),
    "sydney": ("Sydney", "Australia", "APAC"),
    "melbourne": ("Melbourne", "Australia", "APAC"),
    "tokyo": ("Tokyo", "Japan", "APAC"),
    "seoul": ("Seoul", "South Korea", "APAC"),
    "nairobi": ("Nairobi", "Kenya", "Africa"),
    "cape town": ("Cape Town", "South Africa", "Africa"),
}

COUNTRY_ALIASES: dict[str, str] = {
    "uae": "United Arab Emirates",
    "united arab emirates": "United Arab Emirates",
    "emirates": "United Arab Emirates",
    "ksa": "Saudi Arabia",
    "saudi": "Saudi Arabia",
    "saudi arabia": "Saudi Arabia",
    "qatar": "Qatar",
    "germany": "Germany",
    "uk": "United Kingdom",
    "united kingdom": "United Kingdom",
    "england": "United Kingdom",
    "netherlands": "Netherlands",
    "holland": "Netherlands",
    "france": "France",
    "spain": "Spain",
    "portugal": "Portugal",
    "poland": "Poland",
    "india": "India",
    "singapore": "Singapore",
    "malaysia": "Malaysia",
    "canada": "Canada",
    "usa": "United States",
    "us": "United States",
    "united states": "United States",
    "america": "United States",
    "australia": "Australia",
    "japan": "Japan",
    "south korea": "South Korea",
    "kenya": "Kenya",
    "south africa": "South Africa",
    "egypt": "Egypt",
    "jordan": "Jordan",
    "lebanon": "Lebanon",
    "türkiye": "Türkiye",
    "turkey": "Türkiye",
}

INDUSTRIES = [
    "Fintech",
    "Banking",
    "Logistics",
    "E-commerce",
    "Healthtech",
    "Edtech",
    "SaaS",
    "Cybersecurity",
    "Gaming",
    "Media",
    "Real Estate",
    "Travel",
    "Energy",
    "Retail",
    "Consulting",
]

# Domain keyword sets used by JD parsing and analytics
DOMAIN_KEYWORDS: dict[str, list[str]] = {
    "Fintech": [
        "fintech",
        "payments",
        "banking",
        "financial services",
        "lending",
        "neobank",
        "trading",
        "insurance",
        "insurtech",
        "wealth",
    ],
    "Logistics": [
        "logistics",
        "freight",
        "shipping",
        "supply chain",
        "last-mile",
        "warehousing",
        "fleet",
        "customs",
        "3pl",
    ],
    "E-commerce": ["e-commerce", "ecommerce", "marketplace", "retail tech", "online store", "dtc"],
    "Healthtech": [
        "healthtech",
        "healthcare",
        "telemedicine",
        "digital health",
        "clinical",
        "medtech",
        "patient",
    ],
    "Edtech": ["edtech", "education technology", "e-learning", "learning platform", "tutoring"],
    "SaaS": [
        "saas",
        "b2b software",
        "platform as a service",
        "enterprise software",
        "cloud software",
    ],
    "Cybersecurity": [
        "cybersecurity",
        "security operations",
        "threat detection",
        "infosec",
        "zero trust",
    ],
    "Gaming": ["gaming", "game studio", "esports", "game development"],
    "Media": ["media", "streaming", "publishing", "news", "entertainment"],
    "Real Estate": ["real estate", "proptech", "property", "rentals"],
    "Travel": ["travel", "hospitality", "booking", "airlines", "tourism"],
    "Energy": ["energy", "renewables", "solar", "oil and gas", "utilities", "cleantech"],
    "Consulting": ["consulting", "advisory", "professional services"],
}
