"""initial schema

Revision ID: 94e004af9264
Revises: 
Create Date: 2026-10-05 13:55:34.174460+00:00

"""

from __future__ import annotations



from alembic import op
import sqlalchemy as sa
from app.db.types import VectorType


revision = '94e004af9264'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # pgvector must exist before the vector column is created
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('strategies', sa.JSON(), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('per_query', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'country', name='uq_location_city_country')
    )
    op.create_table('normalized_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('related', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalized_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalized_skills_canonical_name'), ['canonical_name'], unique=True)

    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('headline', sa.String(length=220), nullable=True),
    sa.Column('seniority', sa.String(length=40), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_full_name'), ['full_name'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('hq_location', sa.String(length=160), nullable=True),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('rerank', sa.Boolean(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedded_at', sa.DateTime(), nullable=False),
    sa.Column('embedding', VectorType(384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_embeddings_candidate_id'), ['candidate_id'], unique=True)

    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=160), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('field', sa.String(length=160), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_educations_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('normalized_title', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_query_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_results_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_search_query_id'), ['search_query_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name_raw', sa.String(length=120), nullable=False),
    sa.Column('normalized_skill_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('years_used', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['normalized_skill_id'], ['normalized_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_candidate_id'), ['candidate_id'], unique=False)

    if bind.dialect.name == "postgresql":
        # ANN index for cosine distance (no training step, unlike ivfflat)
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_candidate_embeddings_hnsw "
            "ON candidate_embeddings USING hnsw (embedding vector_cosine_ops)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_candidate_id'))

    op.drop_table('skills')
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_results_search_query_id'))
        batch_op.drop_index(batch_op.f('ix_search_results_candidate_id'))

    op.drop_table('search_results')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_candidate_id'))

    op.drop_table('experiences')
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_educations_candidate_id'))

    op.drop_table('educations')
    with op.batch_alter_table('candidate_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_embeddings_candidate_id'))

    op.drop_table('candidate_embeddings')
    op.drop_table('search_queries')
    op.drop_table('companies')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_full_name'))

    op.drop_table('candidates')
    op.drop_table('saved_searches')
    with op.batch_alter_table('normalized_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_skills_canonical_name'))

    op.drop_table('normalized_skills')
    op.drop_table('locations')
    op.drop_table('jobs')
    op.drop_table('industries')
    op.drop_table('benchmark_runs')
    # ### end Alembic commands ###
